-- Create a new XS warehouse for laboratory work.
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_LAB
WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Create a resource monitor to control monthly credit consumption.
CREATE OR REPLACE RESOURCE MONITOR COMPUTE_LAB_MONITOR
WITH
  CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- Attach the monitor to the warehouse.
ALTER WAREHOUSE COMPUTE_LAB
SET RESOURCE_MONITOR = COMPUTE_LAB_MONITOR;

-- Use this warehouse for laboratory work.
USE WAREHOUSE COMPUTE_LAB;
